/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateComidaArgs } from "./CreateComidaArgs";
import { UpdateComidaArgs } from "./UpdateComidaArgs";
import { DeleteComidaArgs } from "./DeleteComidaArgs";
import { ComidaFindManyArgs } from "./ComidaFindManyArgs";
import { ComidaFindUniqueArgs } from "./ComidaFindUniqueArgs";
import { Comida } from "./Comida";
import { ComidaService } from "../comida.service";

@graphql.Resolver(() => Comida)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ComidaResolverBase {
  constructor(
    protected readonly service: ComidaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "read",
    possession: "any",
  })
  async _comidasMeta(
    @graphql.Args() args: ComidaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Comida])
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "read",
    possession: "any",
  })
  async comidas(
    @graphql.Args() args: ComidaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Comida",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Comida, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "read",
    possession: "own",
  })
  async comida(
    @graphql.Args() args: ComidaFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Comida",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Comida)
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "create",
    possession: "any",
  })
  async createComida(
    @graphql.Args() args: CreateComidaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Comida",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Comida"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        usuarioId: args.data.usuarioId
          ? {
              connect: args.data.usuarioId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Comida)
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "update",
    possession: "any",
  })
  async updateComida(
    @graphql.Args() args: UpdateComidaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Comida",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Comida"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          usuarioId: args.data.usuarioId
            ? {
                connect: args.data.usuarioId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Comida)
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "delete",
    possession: "any",
  })
  async deleteComida(
    @graphql.Args() args: DeleteComidaArgs
  ): Promise<Comida | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Comida])
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "read",
    possession: "any",
  })
  async comidas(
    @graphql.Parent() parent: Comida,
    @graphql.Args() args: ComidaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Comida",
    });
    const results = await this.service.findComidas(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Comida, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Comida",
    action: "read",
    possession: "any",
  })
  async usuarioId(
    @graphql.Parent() parent: Comida,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comida | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Comida",
    });
    const result = await this.service.getUsuarioId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
