/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsEnum,
  IsString,
  IsDate,
} from "class-validator";
import { ComidaCreateNestedManyWithoutComidasInput } from "./ComidaCreateNestedManyWithoutComidasInput";
import { Type } from "class-transformer";
import { EnumComidaCosto } from "./EnumComidaCosto";
import { ComidaWhereUniqueInput } from "./ComidaWhereUniqueInput";
@InputType()
class ComidaCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  calorias?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  celiacos?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ComidaCreateNestedManyWithoutComidasInput,
  })
  @ValidateNested()
  @Type(() => ComidaCreateNestedManyWithoutComidasInput)
  @IsOptional()
  @Field(() => ComidaCreateNestedManyWithoutComidasInput, {
    nullable: true,
  })
  comidas?: ComidaCreateNestedManyWithoutComidasInput;

  @ApiProperty({
    required: false,
    enum: EnumComidaCosto,
  })
  @IsEnum(EnumComidaCosto)
  @IsOptional()
  @Field(() => EnumComidaCosto, {
    nullable: true,
  })
  costo?: "Barato" | "Medio" | "Caro" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  foto?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  ultimoUso?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ComidaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComidaWhereUniqueInput)
  @IsOptional()
  @Field(() => ComidaWhereUniqueInput, {
    nullable: true,
  })
  usuarioId?: ComidaWhereUniqueInput | null;
}
export { ComidaCreateInput };
