/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { ComidaListRelationFilter } from "./ComidaListRelationFilter";
import { EnumComidaCosto } from "./EnumComidaCosto";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ComidaWhereUniqueInput } from "./ComidaWhereUniqueInput";
@InputType()
class ComidaWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  celiacos?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ComidaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ComidaListRelationFilter)
  @IsOptional()
  @Field(() => ComidaListRelationFilter, {
    nullable: true,
  })
  comidas?: ComidaListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumComidaCosto,
  })
  @IsEnum(EnumComidaCosto)
  @IsOptional()
  @Field(() => EnumComidaCosto, {
    nullable: true,
  })
  costo?: "Barato" | "Medio" | "Caro";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  foto?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  ultimoUso?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ComidaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComidaWhereUniqueInput)
  @IsOptional()
  @Field(() => ComidaWhereUniqueInput, {
    nullable: true,
  })
  usuarioId?: ComidaWhereUniqueInput;
}
export { ComidaWhereInput };
